# Week 1 — Heart Disease: workflow, claims, and first EDA

### Learning goals
- Load the UCI Heart Disease (Cleveland) dataset
- Create a binary target (`disease`)
- Do first-pass checks: shape, dtypes, missingness
- Make 2 starter plots and write 2 evidence-based observations

### Critical thinking prompt
Before you analyze: **What is the claim** you want to test, and **what would count as evidence**?

**Deliverable:** 5-line project pitch (question, hypothesis, outcome, 2 predictors, 1 bias risk)

In [ ]:
# Core imports (kept minimal for beginners)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 120)

# Dataset URL (UCI Heart Disease - Cleveland)
UCI_URL = "https://www.archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data"

# Column names for processed.cleveland.data (14 columns commonly used in teaching)
COLS = ["age","sex","cp","trestbps","chol","fbs","restecg","thalach",
        "exang","oldpeak","slope","ca","thal","num"]

In [ ]:
import ssl
import io
import urllib.request # Added this import

def load_raw():
    # Create an unverified SSL context to bypass certificate verification
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE

    # Open the URL with the unverified context
    with urllib.request.urlopen(UCI_URL, context=ctx) as url_response:
        # Read the content and decode it
        s = url_response.read().decode('utf-8')

    # Use io.StringIO to make the string behave like a file for pandas.read_csv
    df_raw = pd.read_csv(io.StringIO(s), header=None, names=COLS)
    return df_raw

def coerce_types(df_raw):
    # Missing values are sometimes encoded as "?"
    df = df_raw.replace("?", np.nan).copy()

    # Convert numeric-looking columns
    numeric_cols = ["age","trestbps","chol","thalach","oldpeak","ca","thal","num"]
    for c in numeric_cols:
        df[c] = pd.to_numeric(df[c], errors="coerce")

    # Binary target: disease present if num > 0 (UCI convention)
    df["disease"] = (df["num"] > 0).astype("Int64")
    return df

df_raw = load_raw()
df = coerce_types(df_raw)

df.head()

    age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  slope   ca  thal  num  disease
0  63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3    3.0  0.0   6.0    0        0
1  67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5    2.0  3.0   3.0    2        1
2  67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6    2.0  2.0   7.0    1        1
3  37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5    3.0  0.0   3.0    0        0
4  41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4    1.0  0.0   3.0    0        0

In [ ]:
def quick_profile(df):
    """Small, beginner-friendly dataframe profile."""
    display(df.head())
    print("\nShape:", df.shape)
    print("\nDtypes:")
    print(df.dtypes)
    print("\nMissingness (top 10):")
    miss = df.isna().mean().sort_values(ascending=False)
    display(miss.head(10).to_frame("missing_fraction"))
    print("\nBasic describe (numeric):")
    display(df.describe(include=[np.number]).T)

def check_columns(df):
    assert df.columns.is_unique, "Duplicate column names found"
    assert df.shape[0] > 0, "No rows loaded"
    return True

In [ ]:
check_columns(df)
quick_profile(df)

    age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  slope   ca  thal  num  disease
0  63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3    3.0  0.0   6.0    0        0
1  67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5    2.0  3.0   3.0    2        1
2  67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6    2.0  2.0   7.0    1        1
3  37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5    3.0  0.0   3.0    0        0
4  41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4    1.0  0.0   3.0    0        0

Shape: (303, 15)

Dtypes:
age         float64
sex         float64
cp          float64
trestbps    float64
chol        float64
fbs         float64
restecg     float64
thalach     float64
exang       float64
oldpeak     float64
slope       float64
ca          float64
thal        float64
num           int64
disease       Int64
dtype: object

Missingness (top 10):

          missing_fraction
ca                0.013201
thal              0.006601
age               0.000000
sex               0.000000
cp                0.000000
trestbps          0.000000
chol              0.000000
fbs               0.000000
restecg           0.000000
thalach           0.000000

Basic describe (numeric):

          count        mean        std    min    25%    50%    75%    max
age       303.0   54.438944   9.038662   29.0   48.0   56.0   61.0   77.0
sex       303.0    0.679868   0.467299    0.0    0.0    1.0    1.0    1.0
cp        303.0    3.158416   0.960126    1.0    3.0    3.0    4.0    4.0
trestbps  303.0  131.689769  17.599748   94.0  120.0  130.0  140.0  200.0
chol      303.0  246.693069  51.776918  126.0  211.0  241.0  275.0  564.0
fbs       303.0    0.148515   0.356198    0.0    0.0    0.0    0.0    1.0
restecg   303.0    0.990099   0.994971    0.0    0.0    1.0    2.0    2.0
thalach   303.0  149.607261  22.875003   71.0  133.5  153.0  166.0  202.0
exang     303.0    0.326733   0.469794    0.0    0.0    0.0    1.0    1.0
oldpeak   303.0    1.039604   1.161075    0.0    0.0    0.8    1.6    6.2
slope     303.0     1.60066   0.616226    1.0    1.0    2.0    2.0    3.0
ca        299.0    0.672241   0.937438    0.0    0.0    0.0    1.0    3.0
thal      301.0    4.734219   1.939706    3.0    3.0    3.0    7.0    7.0
num       303.0    0.937294   1.228536    0.0    0.0    0.0    2.0    4.0
disease   303.0    0.458746    0.49912    0.0    0.0    0.0    1.0    1.0

## TODO 1 — Understand the variables
Fill in (in your own words):
- `age` measures:
- `sex` is coded as:
- `cp` (chest pain type) likely means:
- `num` and `disease` relationship is:

**What could be biased in this dataset?** (sample selection? measurement?)
 # TODO1 – Understand the variables

- Age measures: Age (in years)
- Sex is coded as: 0 = female, 1 = male
- cp (chest pain type) likely means: Type of chest pain (1: typical angina, 2: atypical angina, 3: non-anginal pain, 4: asymptomatic)
- Num and disease relationship: Num is the original diagnosis (0 = no disease, 1-4 = disease severity); disease is binary (disease=1 if num>0)

What could be biased in this dataset? Sampling bias (single hospital, male-dominated), measurement bias (missing coding with "?" in ca and thal)

In [ ]:
# Starter plot 1: age distribution
plt.figure()
df["age"].dropna().plot(kind="hist", bins=20)
plt.xlabel("age")
plt.ylabel("count")
plt.title("Age distribution")
plt.show()

# Starter plot 2: disease prevalence
plt.figure()
df["disease"].value_counts(dropna=False).sort_index().plot(kind="bar")
plt.xlabel("disease (0=no, 1=yes)")
plt.ylabel("count")
plt.title("Disease prevalence")
plt.show()

## TODO 2 — Write two observations (complete sentences)
1) Observation from age distribution:

2) Observation from disease prevalence:

**For each observation, write one reason it might be misleading.**

# TODO2 — Write two observations (complete sentences)

1. *Observation from age distribution:*

The age distribution is roughly bell-shaped and slightly skewed to the right; most patients are in the 40-70 age range, with the highest concentration around 55-60.

*Reason it might be misleading:* This dataset is taken from a hospital population and may not fully reflect the prevalence or age profile of heart disease in the general population.

2. *Observation from disease prevalence:*

Disease prevalence is roughly balanced; approximately 46% of patients have the disease, while those without the disease are slightly in the majority.

*Reason it might be misleading:* Since disease is defined as num > 0, mild cases are also counted as "disease". Also, missing values ​​in ca and thal may affect disease classification.

# TODO3 — Choose a preliminary question

*Selected:* Does max heart rate (thalach) differ between groups?

- *Question:*

Does maximum heart rate (thalach) differ between patients with and without heart disease?

- *Hypothesis (H1):*

Patients with heart disease have a lower average maximum heart rate than those without.

- *What would convince you you're wrong?*

If an independent two-sample t-test (or Mann-Whitney U) shows no significant difference (p > 0.05), confidence intervals largely overlap, and the effect size (Cohen’s d) is negligible, the hypothesis is falsified.
 # 5-line project pitch

- *Question:* Can clinical features such as chest pain type (cp) and exertional angina (exang) predict the presence of heart disease?

- *Hypothesis:* Patients with atypical angina or asymptomatic chest pain have a higher probability of heart disease; furthermore, exertional angina is positively correlated.

- *Outcome:* Binary heart disease (disease = 1 if num > 0, otherwise 0).

- *2 predictors:* cp (chest pain type) and exang (exercise-induced angina).

- *1 bias risk:* The dataset was collected from a single institution (Cleveland Clinic); it may not be generalizable to different geographic regions or primary care settings.